# Generated by Django 4.2.4 on 2023-10-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
