# Generated by Django 4.2.4 on 2023-10-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_order_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
