# Generated by Django 4.2.4 on 2023-10-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_first_name_order_name_remove_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='oid',
        ),
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='oid',
        ),
    ]
