# Generated by Django 4.2.4 on 2023-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_oid_orderupdate_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
