# Generated by Django 4.2.4 on 2023-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_order_amountpaid_remove_order_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='paymentMethod',
            field=models.CharField(default='Cash on Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='paymentStatus',
            field=models.CharField(default='Unpaid', max_length=100),
        ),
    ]
