# Generated by Django 4.2.4 on 2023-10-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_orderupdate_paymentmethod_orderupdate_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
