# Generated by Django 4.2.4 on 2023-10-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_order_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
    ]
