# Generated by Django 4.2.4 on 2023-10-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_cart',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='items_json',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
